export const productsData = [
  {
    _id: '1',
    name: 'Ailipu KL-6309 3.1 Sound System',
    price: 4600,
    category: 'Audio',
    image: '/assets/products/Ailipu KL-6309 3.1  4,600.jpeg',
    stock: 10,
    featured: true,
    ratings: 4.5,
    description: 'High-quality 3.1 channel sound system with powerful bass and crystal clear audio.'
  },
  {
    _id: '2',
    name: 'Ailipu KL-8302 3.1 Tallboy',
    price: 11700,
    category: 'Audio',
    image: '/assets/products/Ailipu KL-8302 3.1 Tallboy  11,700.jpeg',
    stock: 8,
    featured: true,
    ratings: 4.7,
    description: 'Premium 3.1 tallboy sound system with enhanced bass and sleek design.'
  },
  {
    _id: '3',
    name: 'Ailyons Air Fryer 5L AF-389',
    price: 4800,
    category: 'Kitchen Appliances',
    image: '/assets/products/Ailyons Air Fryer 5L AF-389  4800.jpeg',
    stock: 15,
    featured: true,
    ratings: 4.6,
    description: '5-liter air fryer for healthy cooking with rapid air technology.'
  },
  {
    _id: '4',
    name: 'Amtec 32 Smart TV AC DC',
    price: 13400,
    category: 'Electronics',
    image: '/assets/products/Amtec 32 Smart TV AC DC  13,400.jpeg',
    stock: 12,
    featured: true,
    ratings: 4.4,
    description: '32-inch Smart TV with AC/DC compatibility, perfect for home entertainment.'
  },
  {
    _id: '5',
    name: 'Amtec AM-721 3.1 Tallboy',
    price: 9500,
    category: 'Audio',
    image: '/assets/products/Amtec AM-721 3.1 Tallboy  9,500.jpeg',
    stock: 10,
    featured: false,
    ratings: 4.3,
    description: '3.1 tallboy sound system with powerful audio output.'
  },
  {
    _id: '6',
    name: 'Amtec Wireless Soundbar AM-03',
    price: 6100,
    category: 'Audio',
    image: '/assets/products/Amtec Wireless Soundbar AM-03  6,100.jpeg',
    stock: 20,
    featured: false,
    ratings: 4.2,
    description: 'Wireless soundbar with Bluetooth connectivity and immersive sound.'
  },
  {
    _id: '7',
    name: 'Boschmann Car Amplifier 1500 Watts',
    price: 9500,
    category: 'Electronics',
    image: '/assets/products/Boschmann Car Amplifier 1500 Watts  9500.jpeg',
    stock: 8,
    featured: false,
    ratings: 4.5,
    description: 'Powerful 1500W car amplifier for enhanced car audio experience.'
  },
  {
    _id: '8',
    name: 'Car Android Player 10 inch',
    price: 11500,
    category: 'Electronics',
    image: '/assets/products/Car Android Player 10  11,500.jpeg',
    stock: 10,
    featured: false,
    ratings: 4.4,
    description: '10-inch Android car player with touchscreen and smart features.'
  },
  {
    _id: '9',
    name: 'Car Android Player 8 inch',
    price: 10500,
    category: 'Electronics',
    image: '/assets/products/Car Android Player 8  10,500gg.jpeg',
    stock: 12,
    featured: false,
    ratings: 4.3,
    description: '8-inch Android car player with navigation and multimedia support.'
  },
  {
    _id: '10',
    name: 'Car Android Player 9 inch',
    price: 10500,
    category: 'Electronics',
    image: '/assets/products/Car Android Player 9.jpeg',
    stock: 10,
    featured: false,
    ratings: 4.4,
    description: '9-inch Android car player with advanced features.'
  },
  {
    _id: '11',
    name: 'Electromate Soundbar SB01',
    price: 4200,
    category: 'Audio',
    image: '/assets/products/Electromate Soundbar SB01  4,200.jpeg',
    stock: 15,
    featured: false,
    ratings: 4.2,
    description: 'Compact soundbar with clear audio quality.'
  },
  {
    _id: '12',
    name: 'Electromate Soundbar SB02',
    price: 6400,
    category: 'Audio',
    image: '/assets/products/Electromate Soundbar SB02  6,400.jpeg',
    stock: 12,
    featured: false,
    ratings: 4.3,
    description: 'Enhanced soundbar with powerful bass.'
  },
  {
    _id: '13',
    name: 'Electromate Standing Cooker 3G+1E',
    price: 19000,
    category: 'Cooking Appliances',
    image: '/assets/products/Electromate Standing Cooker 3G+1E 50×55  19000.jpeg',
    stock: 6,
    featured: true,
    ratings: 4.6,
    description: '3 gas + 1 electric standing cooker with oven.'
  },
  {
    _id: '14',
    name: 'Eoco Double Fryer 6L+6L',
    price: 7200,
    category: 'Kitchen Appliances',
    image: '/assets/products/Eoco Double Fryer 6L+6L  7,200.jpeg',
    stock: 10,
    featured: false,
    ratings: 4.4,
    description: 'Double deep fryer with 6L capacity each.'
  },
  {
    _id: '15',
    name: 'Eoco Single Fryer 6L',
    price: 3800,
    category: 'Kitchen Appliances',
    image: '/assets/products/Eoco Single Fryer 6L  3,800.jpeg',
    stock: 15,
    featured: false,
    ratings: 4.3,
    description: 'Single deep fryer with 6L capacity.'
  },
  {
    _id: '16',
    name: 'GLD 55 Smart VIDAA 4K TV',
    price: 38000,
    category: 'Electronics',
    image: '/assets/products/GLD 55 Smart VIDAA 4K TV @ 38,000.jpeg',
    stock: 5,
    featured: true,
    ratings: 4.7,
    description: '55-inch 4K Smart TV with VIDAA OS.'
  },
  {
    _id: '17',
    name: 'Greatstar 14pc Cookware Set',
    price: 6800,
    category: 'Kitchen Appliances',
    image: '/assets/products/Greatstar 14pc Cookware Set.@6800.jpeg',
    stock: 12,
    featured: false,
    ratings: 4.3,
    description: '14-piece cookware set for all your cooking needs.'
  },
  {
    _id: '18',
    name: 'Hisense 65 Q6 Series QLED SMART TV 4K',
    price: 73000,
    category: 'Electronics',
    image: '/assets/products/Hisense 65 Q6 Series QLED SMART TV 4K @ 73,000.jpeg',
    stock: 4,
    featured: true,
    ratings: 4.8,
    description: '65-inch QLED 4K Smart TV with premium picture quality.'
  },
  {
    _id: '19',
    name: 'Hisense Double Door Fridge 91 Litres',
    price: 20000,
    category: 'Refrigeration',
    image: '/assets/products/Hisense Double Door Fridge 91 Litres REF091DR @ 20,000.jpeg',
    stock: 8,
    featured: true,
    ratings: 4.6,
    description: '91-liter double door refrigerator.'
  },
  {
    _id: '20',
    name: 'Hisense Single Door Fridge 94 Litres',
    price: 18500,
    category: 'Refrigeration',
    image: '/assets/products/Hisense Single Door Fridge 94 Litres REF094DR @ 18,500.jpeg',
    stock: 10,
    featured: false,
    ratings: 4.5,
    description: '94-liter single door refrigerator.'
  },
  {
    _id: '21',
    name: 'Nunix Dispenser K1S H&N',
    price: 3300,
    category: 'Small Home Appliances',
    image: '/assets/products/Nunix Dispenser K1S H&N @ 3,300.jpeg',
    stock: 15,
    featured: false,
    ratings: 4.2,
    description: 'Hot and cold water dispenser.'
  },
  {
    _id: '22',
    name: 'O\'LEAR 3 In 1 Rechargeable Shaver',
    price: 800,
    category: 'Small Home Appliances',
    image: '/assets/products/OLEAR 3 In 1 Rechargeable Shaver @ 800.jpeg',
    stock: 20,
    featured: false,
    ratings: 4.1,
    description: '3-in-1 rechargeable shaver for grooming.'
  },
  {
    _id: '23',
    name: 'O\'LEAR OL-6008 Rechargeable Shaver',
    price: 1400,
    category: 'Small Home Appliances',
    image: '/assets/products/OLEAR OL-6008 Rechargeable Shaver @ 1400.jpeg',
    stock: 18,
    featured: false,
    ratings: 4.2,
    description: 'Rechargeable shaver with precision blades.'
  },
  {
    _id: '24',
    name: 'Olelon Standing Cooker 3G + 1 Electric',
    price: 20000,
    category: 'Cooking Appliances',
    image: '/assets/products/Olelon Standing Cooker 3G + 1 Electric Hot Plate & Electric Oven 50×55 @ 20000.jpeg',
    stock: 6,
    featured: false,
    ratings: 4.5,
    description: '3 gas + 1 electric standing cooker with oven.'
  },
  {
    _id: '25',
    name: 'Platform Scales',
    price: 4100,
    category: 'Small Home Appliances',
    image: '/assets/products/4100.jpeg',
    stock: 12,
    featured: false,
    ratings: 4.2,
    description: 'Digital platform scales for accurate weighing.'
  },
  {
    _id: '26',
    name: 'Skyworth 43 Smart Google TV',
    price: 26500,
    category: 'Electronics',
    image: '/assets/products/Skyworth 43 Smart Google TV @ 26,500f.jpeg',
    stock: 8,
    featured: true,
    ratings: 4.5,
    description: '43-inch Smart Google TV with built-in Chromecast.'
  },
  {
    _id: '27',
    name: 'Sokany Juicer',
    price: 4800,
    category: 'Kitchen Appliances',
    image: '/assets/products/Sokany juicer @4800.jpeg',
    stock: 15,
    featured: false,
    ratings: 4.3,
    description: 'Electric juicer for fresh fruits and vegetables.'
  },
  {
    _id: '28',
    name: 'Solarmax 50 Smart TV 4K',
    price: 29500,
    category: 'Electronics',
    image: '/assets/products/Solarmax 50 Smart TV 4K @ 29,500.jpeg',
    stock: 6,
    featured: true,
    ratings: 4.5,
    description: '50-inch 4K Smart TV with smart features.'
  },
  {
    _id: '29',
    name: 'Solarmax Power Inverter 1000W',
    price: 5000,
    category: 'Electronics',
    image: '/assets/products/Solarmax Power Inverter 1000W @ 5,000.jpeg',
    stock: 12,
    featured: false,
    ratings: 4.3,
    description: '1000W power inverter for backup power.'
  },
  {
    _id: '30',
    name: 'Solarmax Power Inverter 1500W',
    price: 7500,
    category: 'Electronics',
    image: '/assets/products/Solarmax Power Inverter 1500W @ 75,00.jpeg',
    stock: 10,
    featured: false,
    ratings: 4.4,
    description: '1500W power inverter for home and office use.'
  },
  {
    _id: '31',
    name: 'Solarmax Power Inverter 2000W',
    price: 9200,
    category: 'Electronics',
    image: '/assets/products/Solarmax Power Inverter 2000W @ 9200.jpeg',
    stock: 8,
    featured: false,
    ratings: 4.5,
    description: '2000W power inverter for heavy-duty applications.'
  },
  {
    _id: '32',
    name: 'Solarmax Power Inverter 600W',
    price: 3000,
    category: 'Electronics',
    image: '/assets/products/Solarmax Power Inverter 600W @ 3,000.jpeg',
    stock: 15,
    featured: false,
    ratings: 4.2,
    description: '600W power inverter for basic power needs.'
  },
  {
    _id: '33',
    name: 'Syinix 2 In 1 Blender',
    price: 4200,
    category: 'Kitchen Appliances',
    image: '/assets/products/Syinix 2 In 1 Blender @ 4,200 .jpeg',
    stock: 15,
    featured: false,
    ratings: 4.3,
    description: '2-in-1 blender and grinder for kitchen convenience.'
  },
  {
    _id: '34',
    name: 'Syinix Standing Cooker 3 Gas + 1 Electric',
    price: 23500,
    category: 'Cooking Appliances',
    image: '/assets/products/Syinix Standing Cooker 3 Gas + 1 Electric Burner, Electric Oven Rotisserie 50×60 @ 23,500.jpeg',
    stock: 5,
    featured: true,
    ratings: 4.7,
    description: '3 gas + 1 electric standing cooker with rotisserie.'
  },
  {
    _id: '35',
    name: 'TCL 43 Smart Google QLED TV 43S5K',
    price: 27500,
    category: 'Electronics',
    image: '/assets/products/TCL 43 Smart Google QLED TV 43S5K @ 27,500.jpeg',
    stock: 8,
    featured: true,
    ratings: 4.6,
    description: '43-inch QLED Smart Google TV.'
  },
  {
    _id: '36',
    name: 'TCL 43 Smart Google TV 4K V6D',
    price: 31000,
    category: 'Electronics',
    image: '/assets/products/TCL 43 Smart Google TV 4K V6D @ 31,000.jpeg',
    stock: 6,
    featured: true,
    ratings: 4.7,
    description: '43-inch 4K Smart Google TV with advanced features.'
  },
  {
    _id: '37',
    name: 'Vention 1 In 4 Out HDMI Splitter 4K',
    price: 5000,
    category: 'Electronics',
    image: '/assets/products/Vention 1 In 4 Out HDMI Splitter 4K @ 5000.jpeg',
    stock: 15,
    featured: false,
    ratings: 4.3,
    description: '4K HDMI splitter for multiple displays.'
  },
  {
    _id: '38',
    name: 'Vention 1 In 8 Out HDMI Splitter 4K',
    price: 7800,
    category: 'Electronics',
    image: '/assets/products/Vention 1 In 8 Out HDMI Splitter 4K @ 7,800.jpeg',
    stock: 10,
    featured: false,
    ratings: 4.4,
    description: '8-port 4K HDMI splitter.'
  },
  {
    _id: '39',
    name: 'Vention 5 In 1 Out HDMI Switch 4K',
    price: 5700,
    category: 'Electronics',
    image: '/assets/products/Vention 5 In 1 Out HDMI Switch 4K @ 5700.jpeg',
    stock: 12,
    featured: false,
    ratings: 4.3,
    description: '5-in-1 HDMI switch for multiple inputs.'
  },
  {
    _id: '40',
    name: 'Vision Plus 43 Smart Whale TV',
    price: 24200,
    category: 'Electronics',
    image: '/assets/products/Vision Plus 43 Smart Whale TV @ 24,200.jpeg',
    stock: 8,
    featured: true,
    ratings: 4.5,
    description: '43-inch Smart TV with whale design.'
  },
  {
    _id: '41',
    name: 'Vision Plus 50 QLED VIDAA 4K TV',
    price: 38000,
    category: 'Electronics',
    image: '/assets/products/Vision Plus 50 QLED VIDAA 4K TV @ 38,000.jpeg',
    stock: 5,
    featured: true,
    ratings: 4.6,
    description: '50-inch QLED 4K TV with VIDAA OS.'
  },
  {
    _id: '42',
    name: 'Vision Plus 55 QLED VIDAA 4K TV',
    price: 42000,
    category: 'Electronics',
    image: '/assets/products/Vision Plus 55 QLED VIDAA 4K TV @42,000.jpeg',
    stock: 4,
    featured: true,
    ratings: 4.7,
    description: '55-inch QLED 4K TV with premium features.'
  },
  {
    _id: '43',
    name: 'Vitron 32 Smart QLED TV',
    price: 12600,
    category: 'Electronics',
    image: '/assets/products/Vitron 32 Smart QLED TV @ 12600.jpeg',
    stock: 10,
    featured: false,
    ratings: 4.4,
    description: '32-inch Smart QLED TV.'
  },
  {
    _id: '44',
    name: 'Vitron 43 Smart QLED TV',
    price: 20500,
    category: 'Electronics',
    image: '/assets/products/Vitron 43 Smart QLED TV @ 20,500.jpeg',
    stock: 8,
    featured: true,
    ratings: 4.5,
    description: '43-inch Smart QLED TV with smart features.'
  },
  {
    _id: '45',
    name: 'Vitron Cordless Kettle P5 P6 2L',
    price: 1800,
    category: 'Kitchen Appliances',
    image: '/assets/products/Vitron Cordless Kettle P5 P6 2L @ 1,800.jpeg',
    stock: 20,
    featured: false,
    ratings: 4.2,
    description: '2-liter cordless electric kettle.'
  },
  {
    _id: '46',
    name: 'Vitron Cordless Kettle P7 2L Adjustable',
    price: 2400,
    category: 'Kitchen Appliances',
    image: '/assets/products/Vitron Cordless Kettle P7 2L with adjustable temperature @ 2,400.jpeg',
    stock: 15,
    featured: false,
    ratings: 4.3,
    description: '2-liter cordless kettle with adjustable temperature.'
  },
  {
    _id: '47',
    name: 'Vitron Soundbar V535SB 5.1',
    price: 7300,
    category: 'Audio',
    image: '/assets/products/Vitron Soundbar V535SB 5.1 @ 7300.jpeg',
    stock: 10,
    featured: false,
    ratings: 4.4,
    description: '5.1 channel soundbar with surround sound.'
  },
  {
    _id: '48',
    name: 'Vitron V837 3.1 Sound System',
    price: 7000,
    category: 'Audio',
    image: '/assets/products/Vitron V837 3.1 @ 7,000.jpeg',
    stock: 12,
    featured: false,
    ratings: 4.3,
    description: '3.1 channel sound system.'
  },
  {
    _id: '49',
    name: 'Von Digital Microwave + Grill 20 Litres',
    price: 12500,
    category: 'Kitchen Appliances',
    image: '/assets/products/Von Digital Microwave + Grill 20 Litres VAMG-20DGB @ 12,500.jpeg',
    stock: 10,
    featured: false,
    ratings: 4.4,
    description: '20-liter digital microwave with grill function.'
  },
  {
    _id: '50',
    name: 'WK-02 Wireless Soundbar',
    price: 6100,
    category: 'Audio',
    image: '/assets/products/WK-02 Wireless Soundbar @ 6,100.jpeg',
    stock: 15,
    featured: false,
    ratings: 4.3,
    description: 'Wireless soundbar with Bluetooth.'
  },
  {
    _id: '51',
    name: 'Wahl Balding Series Original',
    price: 8700,
    category: 'Small Home Appliances',
    image: '/assets/products/Wahl Balding Series Original @ 8,700.jpeg',
    stock: 12,
    featured: false,
    ratings: 4.4,
    description: 'Professional balding clipper.'
  },
  {
    _id: '52',
    name: 'Xiaomi 43 Google TV',
    price: 25600,
    category: 'Electronics',
    image: '/assets/products/Xiaomi 43 Google TV @ 25,600.jpeg',
    stock: 8,
    featured: true,
    ratings: 4.6,
    description: '43-inch Google TV by Xiaomi.'
  },
  {
    _id: '53',
    name: 'Xiaomi 55 Google TV 4K',
    price: 47500,
    category: 'Electronics',
    image: '/assets/products/Xiaomi 55 Google TV 4K @ 47,500.jpeg',
    stock: 5,
    featured: true,
    ratings: 4.7,
    description: '55-inch 4K Google TV by Xiaomi.'
  },
  {
    _id: '54',
    name: 'Xiaomi 65 Google TV 4K',
    price: 79000,
    category: 'Electronics',
    image: '/assets/products/Xiaomi 65 Google TV 4K @ 79,000.jpeg',
    stock: 3,
    featured: true,
    ratings: 4.8,
    description: '65-inch 4K Google TV by Xiaomi.'
  },
  {
    _id: '55',
    name: 'Zeriotti Blow Dryer Original',
    price: 6800,
    category: 'Small Home Appliances',
    image: '/assets/products/Zeriotti Blow Dryer Original @ 6,800.jpeg',
    stock: 15,
    featured: false,
    ratings: 4.3,
    description: 'Professional blow dryer.'
  },
  {
    _id: '56',
    name: 'Hisense Washing Machine',
    price: 4200,
    category: 'Laundry Appliances',
    image: '/assets/products/hssense wshng machne.jpeg',
    stock: 8,
    featured: false,
    ratings: 4.4,
    description: 'Hisense washing machine for laundry.'
  },
  {
    _id: '57',
    name: 'Steel Light',
    price: 4200,
    category: 'Small Home Appliances',
    image: '/assets/products/streel ligt.jpeg',
    stock: 20,
    featured: false,
    ratings: 4.2,
    description: 'Steel light fixture.'
  }
];
